### ISSUE TITLE
Missing an s on the module name and class name has an extra s. 

### ISSUE THREAD

**Issue by siroccomask** [CrossNox/dadjokes#13]
Example should look like: 
```
from dadjokes import Dadjoke
dadjoke = Dadjoke()
print(dadjoke.joke)
```

**Comment by CrossNox** [comment]
Hey @kicksent, sorry for taking so long! This should be fixed now in pypi, thanks for reporting this :+1: 

BTW, I had no clue anyone was actually using this :smile:
